ACCESS_TOKEN: <ACCESS_TOKEN>
AUTO_UPDATE: 'false'
BRANCH_NAME: <REPO_BRANCH>
DATABASE_NAME: <DATABASE_NAME>
DEST_PATH: <REPO_FOLDER_NAME>
EXTERNAL_URL: <EXT_URL>
GIT_URL: <REPO_URL>
RECIPIENT_EMAIL: <USER_EMAIL>
SMTP_ADDRESS: smtp.gmail.com
SMTP_ENABLE: 'true'
SMTP_PASSWORD: <USER_SMTP_PASS>
SMTP_PORT: '587'
SMTP_USERNAME: <USER_SMTP_MAIL>
UPDATE_ACCESS_TOKEN: <ACCESS_TOKEN>
UPDATE_BRANCH: <APP_UPDATE_BRANCH>
UPDATE_URL: <APP_UPDATE_URL>
